package jaxrsexample.service;

import java.util.Set;
import javax.ws.rs.core.Application;

@javax.ws.rs.ApplicationPath("api")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<>();
        try {
            resources.add(Class.forName("org.glassfish.jersey.jackson.JacksonFeature"));
            resources.add(Class.forName("org.glassfish.jersey.media.multipart.MultiPartFeature"));
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(jaxrsexample.service.BooksResource.class);
        resources.add(jaxrsexample.service.RuntimeExceptionMapper.class);
    }
    
}
